# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import controller_pb2 as controller__pb2


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Migrate = channel.unary_unary(
                '/controller.Controller/Migrate',
                request_serializer=controller__pb2.MigrateRequest.SerializeToString,
                response_deserializer=controller__pb2.MigrateReply.FromString,
                )
        self.Recieve = channel.unary_unary(
                '/controller.Controller/Recieve',
                request_serializer=controller__pb2.RecieveRequest.SerializeToString,
                response_deserializer=controller__pb2.RecieveReply.FromString,
                )


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Migrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=controller__pb2.MigrateRequest.FromString,
                    response_serializer=controller__pb2.MigrateReply.SerializeToString,
            ),
            'Recieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Recieve,
                    request_deserializer=controller__pb2.RecieveRequest.FromString,
                    response_serializer=controller__pb2.RecieveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.Controller/Migrate',
            controller__pb2.MigrateRequest.SerializeToString,
            controller__pb2.MigrateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.Controller/Recieve',
            controller__pb2.RecieveRequest.SerializeToString,
            controller__pb2.RecieveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
