# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\"\x1f\n\x0eMigrateRequest\x12\r\n\x05\x63onts\x18\x01 \x01(\t\"\x1c\n\x0cMigrateReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1e\n\x0eRecieveRequest\x12\x0c\n\x04\x63ont\x18\x01 \x01(\t\"\x1c\n\x0cRecieveReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2\x92\x01\n\nController\x12\x41\n\x07Migrate\x12\x1a.controller.MigrateRequest\x1a\x18.controller.MigrateReply\"\x00\x12\x41\n\x07Recieve\x12\x1a.controller.RecieveRequest\x1a\x18.controller.RecieveReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MIGRATEREQUEST._serialized_start=32
  _MIGRATEREQUEST._serialized_end=63
  _MIGRATEREPLY._serialized_start=65
  _MIGRATEREPLY._serialized_end=93
  _RECIEVEREQUEST._serialized_start=95
  _RECIEVEREQUEST._serialized_end=125
  _RECIEVEREPLY._serialized_start=127
  _RECIEVEREPLY._serialized_end=155
  _CONTROLLER._serialized_start=158
  _CONTROLLER._serialized_end=304
# @@protoc_insertion_point(module_scope)
