# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: front.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ront.proto\x12\x05\x66ront\"O\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06policy\x18\x02 \x01(\t\x12\x0e\n\x06thresh\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x1d\n\rRegisterReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"!\n\x11\x44\x65registerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0f\x44\x65registerReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1c\n\x0cStartRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\nStartReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1b\n\x0bStopRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\tStopReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1d\n\rFreezeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x0b\x46reezeReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1f\n\x0fUnfreezeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\rUnfreezeReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1d\n\rStatusRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x0bStatusReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"=\n\rPolicyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06policy\x18\x02 \x01(\t\x12\x0e\n\x06thresh\x18\x03 \x01(\t\"\x1b\n\x0bPolicyReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2\xc6\x03\n\x05\x46ront\x12:\n\x08Register\x12\x16.front.RegisterRequest\x1a\x14.front.RegisterReply\"\x00\x12@\n\nDeregister\x12\x18.front.DeregisterRequest\x1a\x16.front.DeregisterReply\"\x00\x12\x31\n\x05Start\x12\x13.front.StartRequest\x1a\x11.front.StartReply\"\x00\x12.\n\x04Stop\x12\x12.front.StopRequest\x1a\x10.front.StopReply\"\x00\x12\x34\n\x06\x46reeze\x12\x14.front.FreezeRequest\x1a\x12.front.FreezeReply\"\x00\x12:\n\x08Unfreeze\x12\x16.front.UnfreezeRequest\x1a\x14.front.UnfreezeReply\"\x00\x12\x34\n\x06Status\x12\x14.front.StatusRequest\x1a\x12.front.StatusReply\"\x00\x12\x34\n\x06Policy\x12\x14.front.PolicyRequest\x1a\x12.front.PolicyReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'front_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=22
  _REGISTERREQUEST._serialized_end=101
  _REGISTERREPLY._serialized_start=103
  _REGISTERREPLY._serialized_end=132
  _DEREGISTERREQUEST._serialized_start=134
  _DEREGISTERREQUEST._serialized_end=167
  _DEREGISTERREPLY._serialized_start=169
  _DEREGISTERREPLY._serialized_end=200
  _STARTREQUEST._serialized_start=202
  _STARTREQUEST._serialized_end=230
  _STARTREPLY._serialized_start=232
  _STARTREPLY._serialized_end=258
  _STOPREQUEST._serialized_start=260
  _STOPREQUEST._serialized_end=287
  _STOPREPLY._serialized_start=289
  _STOPREPLY._serialized_end=314
  _FREEZEREQUEST._serialized_start=316
  _FREEZEREQUEST._serialized_end=345
  _FREEZEREPLY._serialized_start=347
  _FREEZEREPLY._serialized_end=374
  _UNFREEZEREQUEST._serialized_start=376
  _UNFREEZEREQUEST._serialized_end=407
  _UNFREEZEREPLY._serialized_start=409
  _UNFREEZEREPLY._serialized_end=438
  _STATUSREQUEST._serialized_start=440
  _STATUSREQUEST._serialized_end=469
  _STATUSREPLY._serialized_start=471
  _STATUSREPLY._serialized_end=514
  _POLICYREQUEST._serialized_start=516
  _POLICYREQUEST._serialized_end=577
  _POLICYREPLY._serialized_start=579
  _POLICYREPLY._serialized_end=606
  _FRONT._serialized_start=609
  _FRONT._serialized_end=1063
# @@protoc_insertion_point(module_scope)
